global:
  scrape_interval: 5s
scrape_configs:
  - job_name: commerce
    static_configs:
      - targets: [gateway:8000, user-service:8000, order-service:8000, payment-service:8000, inventory-service:8000, notification-service:8000]
