// Actual click-through of docs/demo-5min.md. No narration is synthesized or timed.
const {chromium}=require('playwright');const fs=require('node:fs');const path=require('node:path');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'artifacts/phase5'),BASE=process.env.SENTINEL_DEMO_URL||'http://localhost:18082';
const file=process.argv[2]||'demo-dry-run.json';if(path.basename(file)!==file||fs.existsSync(path.join(OUT,file)))throw Error('Choose a new report filename');
const result={scope:'ACTUAL_FIVE_MINUTE_SCRIPT_BROWSER_ACTIONS_NO_NARRATION',started_at:new Date().toISOString(),steps:[],errors:[],resource_failures:[],mutations:[],external_requests:[]};
(async()=>{let b;try{b=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||(process.platform==='win32'?'msedge':undefined)});const page=await b.newPage({viewport:{width:1366,height:768},acceptDownloads:true});
 page.on('pageerror',e=>result.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')result.errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)result.resource_failures.push(r.status()+' '+r.url())});page.on('request',r=>{if(!['GET','HEAD'].includes(r.method()))result.mutations.push(r.method()+' '+r.url())});
 await page.route('**/*',r=>{if(new URL(r.request().url()).origin!==new URL(BASE).origin){result.external_requests.push(r.request().url());return r.abort()}return r.continue()});
 async function step(name,fn){const t=Date.now();await fn();result.steps.push({name,passed:true,action_ms:Date.now()-t})}
 async function nav(name){await page.locator('#navigation nav').getByRole('link',{name,exact:true}).click();await page.locator('#content h1').first().waitFor()}
 await page.goto(BASE);
 await step('00:00 Dashboard positioning and recorded provenance',async()=>{await page.locator('#topology svg').waitFor();if(!(await page.locator('#header').innerText()).includes('RECORDED DEMO'))throw Error('Missing mode');if(!(await page.locator('.benchmark-strip').innerText()).includes('7/8'))throw Error('Missing denominator')});
 await step('00:30 Architecture and error recovery flow',async()=>{await nav('Architecture');await page.getByRole('heading',{name:'Runtime architecture',exact:true}).scrollIntoViewIfNeeded();if(!(await page.locator('#content').innerText()).includes('Pinned Context'))throw Error('Recovery flow absent')});
 await step('01:00 Complete replay then skip to root cause',async()=>{await nav('Investigation replay');await page.locator('[data-action="restart"]').click();await page.locator('#speed').selectOption('4');await page.locator('[data-action="play"]').click();await page.waitForFunction(()=>document.querySelectorAll('#timeline li button').length>2);await page.locator('[data-action="pause"]').click();await page.locator('#timeline li button').first().click();await page.locator('#modal pre').waitFor();await page.getByRole('button',{name:'Close dialog'}).click();await page.locator('[data-action="play"]').click();await page.waitForFunction(()=>parseInt(document.querySelector('#event-count').textContent)===204,{},{timeout:25000});if(!await page.locator('[data-action="play"]').isDisabled())throw Error('Replay did not stop');await page.locator('[data-action="restart"]').click();await page.locator('[data-action="root"]').click();if(!(await page.locator('#timeline').innerText()).includes('ROOT CAUSE'))throw Error('Root missing')});
 await step('02:30 Root citation logs and source evidence',async()=>{await nav('Root cause');await page.locator('[data-action="evidence"]').first().click();await page.locator('#modal pre').waitFor();await page.getByRole('button',{name:'Close dialog'}).click();await nav('Evidence');await page.locator('[data-filter="LOGS"]').click();await page.locator('details[data-raw] summary').first().click();await page.locator('.raw-content pre').first().waitFor();if(!(await page.locator('.raw-content pre').first().innerText()).includes('TypeError'))throw Error('Expected recorded error missing');await page.locator('[data-filter="CODE"]').click();if(!await page.locator('.evidence-card').count())throw Error('Code absent')});
 await step('03:15 Actual candidate diff baseline and replay',async()=>{await nav('AI patch');for(const d of await page.locator('details').all())await d.locator('summary').click();if(!(await page.locator('#content').innerText()).includes('9 passed'))throw Error('Contract result missing');if(!await page.getByRole('button',{name:/Apply patch/}).isDisabled())throw Error('Apply active');const waiting=page.waitForEvent('download');await page.getByRole('link',{name:'Download candidate diff'}).click();const dl=await waiting;const diff=fs.readFileSync(await dl.path(),'utf8');if(!diff.includes('+    if discount is None:'))throw Error('Diff download missing')});
 await step('04:00 Retained retry storm error and sample size',async()=>{await nav('Evaluation');const row=page.locator('#scenario-matrix tr').filter({hasText:'retry_storm'});await row.getByRole('button').last().click();await page.locator('#modal[open] h2').waitFor();if(!(await page.locator('#modal-content').innerText()).includes('INCORRECT'))throw Error('Wrong outcome');await page.getByRole('button',{name:'Close dialog'}).click();if(!(await page.locator('#evaluation-table').innerText()).includes('7/8 (87.5%)'))throw Error('Accuracy lacks sample denominator')});
 await step('04:40 V3 and V3.1 failures remain prominent',async()=>{await page.locator('.evolution').scrollIntoViewIfNeeded();if(await page.locator('.evolution .bad-text').count()!==2)throw Error('Failure hidden')});
 await step('Documentation and local-only interview path',async()=>{await nav('Documentation');await page.locator('.doc-library summary').click();await page.locator('.doc-list').getByRole('link',{name:'30-second pitch',exact:true}).click();await page.locator('.document').waitFor();await page.locator('.doc-library summary').click();await page.locator('.doc-list').getByRole('link',{name:'Final status',exact:true}).click();await page.locator('.document').waitFor();if(!(await page.locator('.document').innerText()).includes('What requires an API key'))throw Error('Final status absent')});
 result.passed=!result.errors.length&&!result.resource_failures.length&&!result.mutations.length&&!result.external_requests.length;
 }catch(e){result.passed=false;result.failure=e.stack}finally{if(b)await b.close();result.finished_at=new Date().toISOString();fs.writeFileSync(path.join(OUT,file),JSON.stringify(result,null,2),{flag:'wx'});console.log(JSON.stringify(result));if(!result.passed)process.exitCode=1}})();
