const $=s=>document.querySelector(s);let state={},incidents=[],scenarios=[],selected=null,busy=false,eventStream=null,streamIncident=null;const history=[];let diagnosticTimer=null;let liveAllowed=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,method='GET',body){if(method!=='GET'&&!liveAllowed)throw Error('Live AI is disabled; enable it explicitly in the local environment.');const r=await fetch('/api'+path,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(await r.text());return r.json()}
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',5500)}
const names={overview:['系统运行总览','Overview','从请求到根因，每一个判断都有证据。'],incidents:['事故调查','Incidents','记录每次工具调用，交叉验证每个根因假设。'],faults:['Fault Lab','Fault Lab','注入真实故障，检验系统韧性与 Agent 判断能力。'],evidence:['证据工作台','Evidence','直接查询正在运行的基础设施，保留原始证据。']};
function view(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==name));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('selected',b.dataset.view===name));$('#title').innerHTML=esc(names[name][0])+'<span class="live-pill">LIVE</span>';$('#crumb').textContent=names[name][1];$('#subtitle').textContent=names[name][2]}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
function renderIncidents(){const empty='<div class="empty">尚无事故。运行中的检测器会根据真实异常指标自动创建事故。</div>';$('#incident-count').textContent=incidents.length;$('#recent-incidents').innerHTML=incidents.slice(0,5).map(i=>`<button class="incident-row" data-incident="${i.id}"><span class="incident-id">INC-${i.id.slice(0,6)}</span><span>${esc(i.signal.signals?.map(x=>x.service).join(' · ')||'Operator investigation')}</span><span class="status ${esc(i.status)}">${esc(i.status)}</span><time>${new Date(i.created_at).toLocaleTimeString()}</time></button>`).join('')||empty;$('#incident-list').innerHTML=incidents.map(i=>`<button class="incident-item" data-incident="${i.id}"><span class="incident-id">INC-${i.id.slice(0,6)}</span><p>${esc(i.signal.signals?.map(x=>x.service).join(' · ')||'Operator investigation')}</p><span class="status ${esc(i.status)}">${esc(i.status)}</span></button>`).join('')||empty;document.querySelectorAll('[data-incident]').forEach(e=>e.onclick=()=>{selected=e.dataset.incident;view('incidents');detail().catch(e=>toast(e.message))})}
function stepHTML(s){return `<details class="step" data-step="${s.id}"><summary><span class="stage-tag">${SentinelRuntime.stage(s.kind)}</span>#${s.id} · ${esc(s.payload.agent||s.payload.actor||'Platform')} · ${esc(s.kind)} ${esc(s.payload.tool||s.payload.name||'')}<span>${new Date(s.ts).toLocaleTimeString()}</span></summary><pre>${esc(JSON.stringify(s.payload,null,2))}</pre></details>`}
function measuredTable(rows){return `<table class="measure-table"><thead><tr><th>Service</th><th>Requests</th><th>Error %</th><th>P50</th><th>P95</th><th>P99</th><th>RPS</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.service||'sandbox')}</td>${['requests','error_pct','p50_ms','p95_ms','p99_ms','throughput_rps'].map(k=>`<td>${r[k]==null?'Unknown':Number(r[k]).toFixed(k==='requests'?0:2)}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
async function detail(){
 if(!selected)return;const iid=selected;const [data,a]=await Promise.all([api('/incidents/'+iid),api('/incidents/'+iid+'/agent')]);if(iid!==selected)return;
 const old=[...data.steps].reverse().find(s=>s.kind==='tool_result'&&s.payload.name==='propose_patch'&&s.payload.result?.validated)?.payload.result;
 const patches=a.patches||[];const latest=patches.filter(p=>p.run_id===a.run_id).at(-1);const patch=latest?.artifact||old;const origin=latest?.origin||(old?'HUMAN':null);const critic=data.report?.critic;
 const canApply=patch&&!patch.profile&&(origin==='HUMAN'?patch.validated:origin==='AI_GENERATED'&&patch.candidate_verified&&critic?.verdict==='VERIFIED');
 const resumable=['HYBRID_V2','HYBRID_V3','HYBRID_V4_1'].includes(data.mode)&&data.status==='failed';
 const u=a.usage;const unknown=x=>x==null?'Unknown':esc(x);const diagnosis=data.report?.diagnosis;
 const recovery=data.report?.measured_recovery;
 $('#incident-detail').className='';$('#incident-detail').innerHTML=`<div class="detail-head"><span class="incident-id">INC-${data.id.slice(0,6)}</span><span class="tag">${esc(data.mode||'AI')} MODE</span><h2 id="live-status">${esc(data.status)}</h2><div class="provider-line">Provider: ${esc(a.provider.status)} · Model: ${esc(a.provider.model||'Unknown')}</div><button class="button" id="retry">重新调查</button>${resumable?'<button class="button" id="resume">从检查点继续</button>':''}<a class="button" href="/api/incidents/${data.id}/report" target="_blank">导出 Report</a>${canApply?'<button class="button primary" id="deploy">确认并 Apply 已验证 Patch</button>':''}<div class="usage-grid"><span>LLM Calls <b>${u.llm_calls}</b></span><span>Input <b>${unknown(u.input_tokens)}</b></span><span>Output <b>${unknown(u.output_tokens)}</b></span><span>Total <b>${unknown(u.total_tokens)}</b></span><span>Est. USD <b>${unknown(u.estimated_cost)}</b></span></div><small class="muted">Tokens: Provider reported · Cost: configured prices only · no silent fallback</small></div>
 ${diagnosis?`<div class="analysis-card"><span class="tag">${data.mode==='RULE_BASED'?'RULE-BASED ANALYSIS':'AI ANALYSIS'}</span><h3>${esc(diagnosis.root_cause)}</h3><p>${esc(diagnosis.reasoning_summary)}</p><div>${diagnosis.evidence_ids.map(id=>`<a class="evidence-id" href="#${esc(id)}">${esc(id)}</a>`).join(' ')}</div><p>${esc(diagnosis.patch_decision)} · ${esc(diagnosis.recommended_fix)}</p>${critic?`<h3>Critic · ${esc(critic.verdict)}</h3><p>${esc(critic.verification_summary)}</p>`:''}</div>`:''}
 <section id="runtime-diagnostics"><p class="muted">加载运行诊断…</p></section>
 ${patch?`<details class="step"><summary>PATCH · ${esc(origin)} · ${esc(patch.path||'services/pricing.py')} · ${esc(patch.status||'TESTED')}</summary><pre>${esc(patch.submitted_diff||patch.diff)}</pre>${latest?`<a class="button" href="/api/incidents/${iid}/patches/${latest.id}.diff">导出候选 Diff</a>`:''}<p class="muted">${patch.profile?'候选未部署 · 通用 Patch 需独立代码审查与发布':'部署需要操作员确认'}</p><pre>${esc(JSON.stringify({baseline:patch.baseline_test,candidate:patch.candidate_test,scope:patch.sandbox_scope,risk:patch.risk,automatic_apply_allowed:patch.automatic_apply_allowed,dependencies:patch.replay?.after?.dependencies},null,2))}</pre></details>`:''}
 ${patch?.replay?`<div class="analysis-card"><span class="tag measured">MEASURED · SANDBOX REPLAY</span><p>${esc(patch.replay.after.isolation||patch.replay.after.scope)}</p><p>业务违例率：${patch.replay.before.business_violation_pct??'Unknown'}% → ${patch.replay.after.business_violation_pct??'Unknown'}% · Healthy control: ${patch.replay.after.healthy_control_passed??'Unknown'}</p><h4>Before</h4>${measuredTable([patch.replay.before])}<h4>After</h4>${measuredTable([patch.replay.after])}</div>`:''}
 ${recovery?`<div class="analysis-card"><span class="tag measured">MEASURED · OPERATOR RECOVERY</span><p>实验控制端停止故障后采集，不计为 AI 修复。${esc(recovery.causality_limit)}</p><h4>Before</h4>${measuredTable(recovery.before.http)}<h4>After</h4>${measuredTable(recovery.after.http)}<details><summary>DB Pool / Kafka Lag / Redis · 原始测量</summary><pre>${esc(JSON.stringify(recovery,null,2))}</pre></details></div>`:''}
 <div class="panel-head"><h2>Investigation event ledger</h2><span class="tag" id="sse-status">SSE connecting</span></div><div id="live-timeline">${data.steps.map(stepHTML).join('')}</div>
 <div class="panel-head"><h2>Evidence ledger</h2><span class="tag measured">MEASURED / SOURCE</span></div>${a.evidence.map(e=>`<details class="step" id="${esc(e.id)}"><summary>${esc(e.id)} · ${esc(e.kind)}</summary><pre>${esc(JSON.stringify(e.payload,null,2))}</pre></details>`).join('')}
 ${data.verification?`<div class="analysis-card"><span class="tag measured">MEASURED · DEPLOYMENT</span>${measuredTable(data.verification.after||[])}</div>`:''}`;
 await updateDiagnostics(iid);
 guardLiveControls();$('#retry').onclick=()=>action(()=>api('/incidents/'+iid+'/investigate','POST',{mode:$('#investigation-mode').value}));
 if($('#resume'))$('#resume').onclick=()=>action(()=>api('/incidents/'+iid+'/resume','POST'));
 if($('#deploy'))$('#deploy').onclick=()=>{if(confirm('确认将此已验证 Patch 应用到运行中的订单服务？'))action(()=>api('/incidents/'+iid+'/deploy','POST',{sha256:patch.sha256}))};
 if(eventStream)eventStream.close();streamIncident=iid;
 const cursor=Math.max(0,...data.steps.map(s=>s.id));eventStream=new EventSource('/api/incidents/'+iid+'/events?after='+cursor);
 eventStream.onopen=()=>{if($('#sse-status'))$('#sse-status').textContent='SSE LIVE'};eventStream.onerror=()=>{if($('#sse-status'))$('#sse-status').textContent='SSE reconnecting'};
 eventStream.addEventListener('investigation',evt=>{const row=JSON.parse(evt.data);if(iid!==selected)return;if(!document.querySelector('[data-step="'+row.id+'"]'))$('#live-timeline').insertAdjacentHTML('beforeend',stepHTML(row));$('#live-status').textContent=row.kind;clearTimeout(diagnosticTimer);diagnosticTimer=setTimeout(()=>updateDiagnostics(iid).catch(e=>toast(e.message)),350);if(['Incident Report','Investigation Failed','verification','rollback'].includes(row.kind))detail().catch(e=>toast(e.message))});
}
async function updateDiagnostics(iid){const data=await api('/incidents/'+iid+'/runtime');if(selected===iid&&$('#runtime-diagnostics'))SentinelRuntime.render($('#runtime-diagnostics'),data)}
function renderScenarios(){const active=state.active_faults||[];$('#scenario-list').innerHTML=scenarios.map((s,n)=>`<article class="scenario ${active.includes(s.scenario_id)?'active':''}"><span class="number">EXPERIMENT / ${String(n+1).padStart(2,'0')} ${active.includes(s.scenario_id)?' · ACTIVE':''}</span><h3>${esc(s.name)}</h3><p>${esc(s.description)}</p><span class="service-label">↳ ${esc(s.affected_service)}</span><button class="button ${active.includes(s.scenario_id)?'danger':'primary'}" data-fault="${s.scenario_id}">${active.includes(s.scenario_id)?'停止故障':'触发故障 · 120s'}</button></article>`).join('');document.querySelectorAll('[data-fault]').forEach(b=>b.onclick=()=>action(()=>api('/faults/'+b.dataset.fault,active.includes(b.dataset.fault)?'DELETE':'POST',active.includes(b.dataset.fault)?undefined:{duration_seconds:120})))}
async function action(fn){try{await fn();toast('操作已执行');await refresh()}catch(e){toast(e.message)}}
async function refresh(){if(busy)return;busy=true;try{[state,incidents]=await Promise.all([api('/overview'),api('/incidents')]);const gateway=state.services.find(s=>s.service==='gateway');$('#request-value').textContent=gateway?.requests??'—';$('#error-value').textContent=gateway?Number(gateway.error_pct).toFixed(1)+'%':'—';$('#error-value').style.color=Number(gateway?.error_pct)>5?'var(--red)':'var(--green)';$('#latency-value').textContent=gateway?Math.round(gateway.p95_ms).toLocaleString():'—';$('#fault-value').textContent=state.active_faults.length;$('#traffic').textContent=state.traffic_enabled?'暂停流量':'启动流量';$('#notice').textContent=state.model.configured?`Provider: ${state.provider?.status} · Model: ${state.model.name} · Investigation Mode: ${$('#investigation-mode').value} · 不静默降级`:'LLM 尚未配置 · 遥测、故障注入与事故检测正常运行。AI 调查会显示配置错误状态，不生成模拟结论。';$('#agent-status').textContent=state.provider?.status||'not_configured';$('#agent-description').textContent=state.model.configured?state.model.name:'在本机 .env 中设置模型名称与 API Key';document.querySelectorAll('[data-service]').forEach(el=>{const s=state.services.find(s=>s.service===el.dataset.service);el.classList.toggle('degraded',!!s&&(Number(s.error_pct)>5||s.p95_ms>1000));el.classList.toggle('unknown',!s);if(s)el.querySelector('small').textContent=`${s.requests} req · ${Math.round(s.p95_ms)} ms · ${s.error_pct}% err`});history.push(gateway?.requests||0);if(history.length>20)history.shift();const max=Math.max(...history,1);$('#spark').setAttribute('points',history.map((v,i)=>`${i*180/19},${24-v/max*22}`).join(' '));$('#connection').textContent='Telemetry connected';$('#connection-dot').style.background='var(--green)';$('#clock').textContent=new Date().toLocaleTimeString();$('#updated').textContent='LAST SYNC '+new Date().toLocaleTimeString();renderIncidents();renderScenarios();guardLiveControls();if(selected&&streamIncident!==selected&&!$('#incidents').classList.contains('hidden'))await detail()}catch(e){$('#connection').textContent='Connection lost';$('#connection-dot').style.background='var(--red)';$('#notice').textContent='无法读取实时数据：'+e.message}finally{busy=false}}
$('#traffic').onclick=()=>action(()=>api('/traffic/'+!state.traffic_enabled,'POST'));$('#new-incident').onclick=()=>action(async()=>{selected=(await api('/incidents','POST',{mode:$('#investigation-mode').value})).id;view('incidents')});$('#recover').onclick=()=>action(()=>api('/recover','POST'));$('#rollback').onclick=()=>action(()=>api('/rollback','POST'));document.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=async()=>{$('#evidence-title').textContent=b.textContent;$('#evidence-body').textContent='正在查询真实数据…';try{$('#evidence-body').textContent=JSON.stringify(await api('/evidence/'+b.dataset.evidence),null,2)}catch(e){$('#evidence-body').textContent=e.message}});
(async()=>{try{const cfg=await api('/portfolio/config');liveAllowed=cfg.live_enabled;scenarios=await api('/scenarios');selected=new URLSearchParams(location.search).get('incident');if(selected)view('incidents');await refresh()}catch(e){toast(e.message)}setInterval(refresh,5000)})();

function guardLiveControls(){if(!liveAllowed){document.querySelectorAll('#traffic,#new-incident,#recover,#rollback,#retry,#resume,#deploy,[data-fault]').forEach(b=>{b.disabled=true;b.title='Live AI disabled; not available in recorded demo';});$('#notice').textContent='LIVE TELEMETRY · AI / fault controls disabled. Set LIVE_AI_ENABLED=true locally to enable paid investigation.';}document.querySelectorAll('.live-pill').forEach(e=>e.textContent=liveAllowed?'LIVE AI':'LIVE / AI DISABLED');}
